from __future__ import annotations

import json
import os
import shutil
from dataclasses import dataclass

from github_reviewer.config.schema import AppConfig, ReviewSource, RuntimeReviewRequest
from github_reviewer.errors import IntegrationError
from github_reviewer.github.events import PullRequestEvent, verify_webhook_signature
from github_reviewer.github.integration import GitHubClient, PullRequestCheckout, ReviewPublisher
from github_reviewer.review import ReviewReport, create_review_runner

_SUPPORTED_ACTIONS = {"opened", "reopened", "synchronize"}


class WebhookHandler:
    """Validate and normalize GitHub webhook requests before they enter a job queue."""

    def __init__(self, secret_env: str) -> None:
        self._secret_env = secret_env

    def parse_pull_request(self, body: bytes, event_name: str | None, signature: str | None) -> PullRequestEvent | None:
        secret = os.getenv(self._secret_env)
        if not secret:
            raise IntegrationError("MISSING_WEBHOOK_SECRET", f"Missing webhook secret environment variable: {self._secret_env}")
        verify_webhook_signature(body, signature, secret)
        if event_name != "pull_request":
            return None
        try:
            payload = json.loads(body)
        except json.JSONDecodeError as exc:
            raise IntegrationError("INVALID_WEBHOOK", "Webhook body is not valid JSON") from exc
        event = PullRequestEvent.from_webhook(payload)
        return event if event.action in _SUPPORTED_ACTIONS else None


@dataclass
class GitHubReviewWorkflow:
    """Background-job implementation; webhook servers should call this after acknowledging delivery."""

    config: AppConfig
    checkout: PullRequestCheckout
    publisher: ReviewPublisher | None = None

    @classmethod
    def from_config(cls, config: AppConfig, workspace_root: str) -> "GitHubReviewWorkflow":
        publisher = None
        if config.github.enabled:
            if not config.github.token_env:
                raise IntegrationError("MISSING_GITHUB_TOKEN_CONFIG", "github.token_env is required when GitHub publishing is enabled")
            publisher = ReviewPublisher(GitHubClient(config.github.token_env, config.github.api_url))
        return cls(config=config, checkout=PullRequestCheckout(workspace_root), publisher=publisher)

    async def run(self, event: PullRequestEvent) -> ReviewReport:
        checkout_path = self.checkout.prepare(event)
        try:
            runner = create_review_runner(self.config, checkout_path)
            request = RuntimeReviewRequest(
                repo=checkout_path,
                base=event.base_sha,
                head=event.head_sha,
                source=ReviewSource.GITHUB,
                pull_request_number=event.number,
                commit_sha=event.head_sha,
            )
            report = await runner.review(request)
            if self.publisher:
                self.publisher.publish(event, report)
            return report
        finally:
            # checkout_path is generated by PullRequestCheckout under its private workspace root.
            shutil.rmtree(checkout_path, ignore_errors=True)
